### ISSUE TITLE
Currently failing when pushing to heroku. 

### ISSUE THREAD

**Issue by facultymatt** [ddollar/heroku-buildpack-multi#16]
Currently this fails, with the following log: 

```
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: http://github.com/heroku/heroku-buildpack-nodejs.git

 !     Push rejected, failed to compile Multipack app
```

It hangs for a good 10 minutes or so before it fails.

Any ideas?

**Comment by aarongray** [comment]
I had this same problem when trying to run Rails in a subdirectory, and not in `/`. For example, I had Angular/Node/Gulp app running in `/client` and a Rails app running in `/server`, but both of them were in the same git repo, so I could track changes across the front end and back end. I got this error when trying to deploy them to Heroku. For anyone else having this issue, here is a custom buildpack that will solve the problem.

https://github.com/aarongray/heroku-buildpack-ruby
