### ISSUE TITLE
How to specify base path for a buildpack?

### ISSUE THREAD

**Issue by cirovladimir** [ddollar/heroku-buildpack-multi#33]
I have a Java application which contains a "Node" (a yeoman generated web app actually) in 'src/main/webapp' dir. When pushed, heroku detects it only as a Java app and runs the corresponding buildpack. I'm trying to use this heroku-buildpack-multi but I can't find a way to specify the base directory for the web app.
Adding the buildpack as it is, fails with the error

> Push rejected, failed to compile Multipack app

it expects a package.json file, for the Node buildpack, in root not in src/main/webbapp hence it fails.
My .buildpacks file is

```
https://github.com/heroku/heroku-buildpack-java.git
https://github.com/heroku/heroku-buildpack-nodejs.git
```

**Comment by mewdriller** [comment]
@ddollar: Any chance this basepath feature might make it into your repository? It looks like @cirovladimir's version is starting to diverge a bit...
