### ISSUE TITLE
Buildpacks overwriting each other 

### ISSUE THREAD

**Issue by anthonator** [ddollar/heroku-buildpack-multi#41]
I'm currently trying to install a ruby/nodejs combo. It's a nodejs app that's using Ruby to compile some Sass. I have both a Gemfile and package.json.

My Gemfile is pretty simple.

```ruby
source 'https://rubygems.org'

ruby '2.1.5'

gem 'sass', '~> 3.4.0'
```

In my postinstall script in ```package.json``` when I run ```ruby -v``` I get ```ruby 1.9.2p330 (2014-08-07 revision 47094) [x86_64-linux]```. If I run ```ls /app/vendor/bundle/bin``` in my postinstall script I don't see the ```sass``` executable.

If I remove the nodejs buildpack and deploy the correct Ruby version and Sass are available when I bash in. Adding the nodejs buildpack back and the Ruby version is wrong again and Sass is no longer available.

**Comment by ddollar** [comment]
Closing until we can get some more information.

**Comment by anthonator** [comment]
This seemed to be a problem with the ruby buildpack. It seems to be fixed in master.

https://github.com/heroku/heroku-buildpack-nodejs/issues/134
