### ISSUE TITLE
Add explanation on README.md, that just setting buildpack on config is not enough

### ISSUE THREAD

**Issue by peterhil** [ddollar/heroku-buildpack-multi#51]
Add explanation on README.md, that just setting BUILDPACK_URL on config is not enough, for heroku to pick it up, if the app used a different buildpack on creation. Instead the user should check with `heroku buildpack`what build pack heroku is really using:

heroku config
=== ninhursag Config Vars
BUILDPACK_URL:      https://github.com/ddollar/heroku-buildpack-multi.git  <-- this is a LIE!
NODE_MODULES_CACHE: false
PATH:               /app/.heroku/anaconda/bin:/usr/local/bin:/usr/bin:/bin

heroku buildpack
=== ninhursag Buildpack URL
https://github.com/kennethreitz/conda-buildpack.git

And the this can be fixed by:
heroku buildpack:set https://github.com/ddollar/heroku-buildpack-multi.git

**Comment by jesiah-hackinglife** [comment]
The command has been updated to: heroku buildpack:set https://github.com/ddollar/heroku-buildpack-multi.git

**Comment by samstickland** [comment]
Actually, there's a minor typo, it should be:

    heroku buildpack:set https://github.com/ddollar/heroku-buildpack-multi.git

(buildpack:set not buildpacks:set)

**Comment by jesiah-hackinglife** [comment]
updated. thank you

**Comment by Dmitry-N-Medvedev** [comment]
@samstickland , please see this:

(venv)dmitry@linuxmint ~/projects/heroku.py/python-getting-started $ heroku **buildpack**
 !    **`buildpack`** is not a heroku command.
 !    Perhaps you meant **`buildpacks`**.
 !    See `heroku help` for a list of available commands.

**Comment by samstickland** [comment]
OK, that´s strange:

dev@ubuntu:~/hubbadoproto$ heroku help | grep build
  buildpack    #  manage the buildpack for an app

Perhaps a version difference has changed the command options?

dev@ubuntu:~/hubbadoproto$ heroku version
heroku-toolbelt/3.27.1 (x86_64-linux) ruby/2.2.1
=== Installed Plugins
heroku-pipeline
