### ISSUE TITLE
Deprecate in favor of official solution

### ISSUE THREAD

**Issue by dominic** [ddollar/heroku-buildpack-multi#57]
https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app#adding-a-buildpack

**Comment by techtonik** [comment]
It is not static configuration like is with `.buildpacks`.

**Comment by jedschneider** [comment]
just to clarify, the project I'm working on, I'm seeing the deprecation notice, but not using this buildpack directly. so the solution is to add the buildpacks dynamically via the heroku cli and remove the `.buildpacks` file?
