### ISSUE TITLE
Allow buildpack to execute properly for a period

### ISSUE THREAD

**Issue by beager** [ddollar/heroku-buildpack-multi#59]
Hi @ddollar,

Would you consider not having this buildpack fail for a period of time to allow apps in deployment using this a reasonable time to migrate. My apps and I'm certain the apps of many others are officially undeployable as a result of your changes to this buildpack. I appreciate your pushing others toward Heroku's official solution, but as far as I know this solution is the best way to manage multiple buildpacks in git.

Totally support having the buildpack show a deprecation warning on deployment, however. Maybe pick a date 6 months out for folks to migrate before actually breaking this package?

Appreciate your work on developing and maintaining this package.

**Comment by beager** [comment]
In the meantime for anyone who may see this, I've forked this repo and reverted the deprecation in https://github.com/NomadHealth/heroku-buildpack-multi

If you'd like to continue using this you may switch to that buildpack, or fork your own from that, or fork your own from here and revert 7156247b02a8df7fc7f1db32af1e6e6c0b3f5079 and fe820b194274a5e092e4bccec961d990efb20195.

Happy multi-buildpacking.

**Comment by ddollar** [comment]
Fair point. I've changed it to a warning and will let it run until the end of 2016. Thanks!

**Comment by beager** [comment]
Much appreciated, thank you!

**Comment by ravicious** [comment]
@beager In the future you can migrate to [the official solution](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app) instead of using this buildpack. (#57)

**Comment by techtonik** [comment]
@ravicious doesn't seem to be declarative. Looks like official setup requires additional admin steps to restore config every time, and hence additional level of automation.

**Comment by ravicious** [comment]
@techtonik I think [app.json](https://devcenter.heroku.com/articles/app-json-schema#buildpacks) may solve this problem, check out if it works for you.

**Comment by beager** [comment]
@ravicious great pointer, thanks for the tip
