### ISSUE TITLE
Add additional visibility to 2017 deprecation?

### ISSUE THREAD

**Issue by dylanpyle** [ddollar/heroku-buildpack-multi#66]
@ddollar 👋 

So, we just realized that a couple of our services will be affected by the [stroke of 2017 deprecation](https://github.com/ddollar/heroku-buildpack-multi/commit/127fd376075cc576cf87c28475950a258ca308e9) — we had no visibility into this warning message and just happened across this change, since (I assume like many others) all our deployments happen frequently and quietly on our CI machines.

Have you considered making this more aggressive in the time leading up to that date? Maybe intermittent failures every 1/n deploys or something?

I would assume that a lot of people will be taken by surprise by this one.

**Comment by ddollar** [comment]
Thanks for the suggestion :) 

The process for recovering from this is quite easy. The final shutdown will include easy instructions for how to fork to your own account. This is actually quite a lot safer than running arbitrary code from someone else's Github account against your app and/or secrets anyway.
